# Generated by Django 2.0.1 on 2018-12-16 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20181208_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(default=None, max_length=64, null=True)),
                ('coffeehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Coffeehouse')),
            ],
            options={
                'verbose_name': 'Название вакансии',
                'verbose_name_plural': 'Названия вакансий',
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
        migrations.AlterField(
            model_name='job',
            name='coffeehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.Coffeehouse'),
        ),
        migrations.AddField(
            model_name='job',
            name='jobname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.JobName'),
        ),
    ]
