# Generated by Django 2.0 on 2018-12-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-pk']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_field',
            new_name='body',
        ),
    ]
