# Generated by Django 2.0 on 2018-12-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181224_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(db_index=True, default=0, max_length=120),
        ),
    ]
