# Generated by Django 2.0 on 2018-12-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20181225_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(db_index=True, default=0, max_length=120),
        ),
    ]
