# Generated by Django 2.0 on 2018-12-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20181227_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_pub'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-pk'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
