# Generated by Django 2.0.1 on 2018-12-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20181207_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='active_on_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interior',
            name='active_on_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='active_on_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
