# Generated by Django 2.0 on 2018-12-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181206_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_or_photo',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
