# Generated by Django 2.0 on 2018-12-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_video_or_photo_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_or_photo',
            old_name='is_main',
            new_name='PHOTO',
        ),
        migrations.AddField(
            model_name='video_or_photo',
            name='VIDEO',
            field=models.BooleanField(default=False),
        ),
    ]
