# Generated by Django 2.0 on 2018-12-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181206_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_or_photo',
            name='PHOTO',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='video_or_photo',
            name='VIDEO',
            field=models.FileField(blank=True, null=True, upload_to='profile_videos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='video_or_photo',
            name='main_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video_or_photo',
            name='main_video',
            field=models.BooleanField(default=False),
        ),
    ]
