# Generated by Django 2.0 on 2018-12-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181206_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PHOTO', models.ImageField(blank=True, null=True, upload_to='profile_photo/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIDEO', models.FileField(blank=True, null=True, upload_to='profile_videos/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='video_or_photo',
            name='PHOTO',
        ),
        migrations.RemoveField(
            model_name='video_or_photo',
            name='VIDEO',
        ),
        migrations.AddField(
            model_name='videos',
            name='video',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Video_or_Photo'),
        ),
        migrations.AddField(
            model_name='photos',
            name='photo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Video_or_Photo'),
        ),
    ]
