# Generated by Django 2.0 on 2018-12-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181206_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PHOTO', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
