# Generated by Django 2.0 on 2018-12-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Логотип', 'verbose_name_plural': 'Логотипы'},
        ),
        migrations.AlterModelOptions(
            name='video_or_photo',
            options={'verbose_name': 'Фото или видео на главной странице', 'verbose_name_plural': 'Фото или видео на главной странице'},
        ),
        migrations.AlterField(
            model_name='logo',
            name='PHOTO',
            field=models.FileField(blank=True, null=True, upload_to='logo/%Y/%m/%d'),
        ),
    ]
