# Generated by Django 2.0 on 2018-12-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181228_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='VIDEO',
            field=models.FileField(blank=True, null=True, upload_to='profile_videos'),
        ),
    ]
